source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'MyMovies' do

  # Pods for MyMovies
  pod 'Alamofire', '~> 5.2'
  pod 'ObjectMapper', '~> 3.5'
  pod 'SDOSEnvironment'

end
